"""Canonical filenames for the oliverevans.dev blueberries-voi blog post figures.

Used by ``notebooks/article_figures.ipynb`` and ``scripts/sync_blog_figures.py``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ARTICLE_FIGURES_DIR = REPO_ROOT / "notebooks" / "outputs" / "article_figures"
BARCODE_DIR = REPO_ROOT / "outputs" / "blueberry-pint-barcodes"
DEFAULT_WEB_DEST = (
    Path.home()
    / "code"
    / "web"
    / "personal-website"
    / "public"
    / "images"
    / "blog"
    / "blueberries-voi"
)

# Website basenames under public/images/blog/blueberries-voi/
BLOG_FIG_UPC_LGTIN = "upc-vs-lgtin-codes.png"
BLOG_FIG_GAMMA = "gamma_process.png"
BLOG_FIG_COLD_CHAIN = "cold_chain_calibration.png"
BLOG_FIG_DEMAND = "demand_calendar_validation.png"
BLOG_FIG_LADDER = "ladder_belief_profit.png"
BLOG_FIG_FACTORIAL = "factorial_observation_scenarios.png"
BLOG_FIG_FACTORIAL_TUNING = "factorial_controller_tuning.png"
BLOG_FIG_FACTORIAL_W1_COUNT = "factorial_w1_count.png"

# Not generated by article_figures.ipynb — add manually to the website directory.
BLOG_FIG_STUDIO_MANUAL = "blueberry-studio.png"

# Appendix / notebook-only outputs (not synced to the site).
BLOG_FIG_APPENDIX_SIGNED_BIAS = "appendix_signed_bias.png"
BLOG_FIG_APPENDIX_CRPS_RATIO = "appendix_crps_mean_ratio.png"

BLOG_PUBLISHED_FIGURES: tuple[str, ...] = (
    BLOG_FIG_UPC_LGTIN,
    BLOG_FIG_GAMMA,
    BLOG_FIG_COLD_CHAIN,
    BLOG_FIG_DEMAND,
    BLOG_FIG_LADDER,
    BLOG_FIG_FACTORIAL,
    BLOG_FIG_FACTORIAL_TUNING,
    BLOG_FIG_FACTORIAL_W1_COUNT,
)

# Subdirectory under the website dest for full barcode asset bundle.
BARCODE_WEB_SUBDIR = "barcodes"


@dataclass(frozen=True)
class SyncCopy:
    """One file copy: ``source_dir / rel_path`` → ``dest_dir / dest_rel``."""

    source_dir: Path
    rel_path: str
    dest_rel: str


# Article figures from notebooks/outputs/article_figures/
SYNC_ARTICLE_FIGURES: tuple[SyncCopy, ...] = tuple(
    SyncCopy(ARTICLE_FIGURES_DIR, name, name) for name in BLOG_PUBLISHED_FIGURES[1:]
)

# Blog composite at site root; full barcode bundle under dest/barcodes/.
SYNC_BARCODE_BLOG = SyncCopy(BARCODE_DIR, BLOG_FIG_UPC_LGTIN, BLOG_FIG_UPC_LGTIN)
