"""Canonical filenames for the oliverevans.dev blueberries-voi blog post figures.

Used by ``notebooks/article_figures.ipynb`` and ``scripts/sync_blog_figures.py``.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ARTICLE_FIGURES_DIR = REPO_ROOT / "notebooks" / "outputs" / "article_figures"
DEFAULT_WEB_DEST = (
    Path.home()
    / "code"
    / "web"
    / "personal-website"
    / "public"
    / "images"
    / "blog"
    / "blueberries-voi"
)

# Website basenames under public/images/blog/blueberries-voi/
BLOG_FIG_UPC_GSIN = "upc-vs-gsin-codes.png"
BLOG_FIG_GAMMA = "gamma_process.png"
BLOG_FIG_COLD_CHAIN = "cold_chain_calibration.png"
BLOG_FIG_DEMAND = "demand_calendar_validation.png"
BLOG_FIG_LADDER = "ladder_belief_profit.png"
BLOG_FIG_FACTORIAL = "factorial_observation_scenarios.png"
BLOG_FIG_FACTORIAL_W1_COUNT = "factorial_w1_count.png"

# Not generated by article_figures.ipynb — add manually to the website directory.
BLOG_FIG_STUDIO_MANUAL = "blueberry-studio.png"

# Appendix / notebook-only outputs (not synced to the site).
BLOG_FIG_APPENDIX_SIGNED_BIAS = "appendix_signed_bias.png"
BLOG_FIG_APPENDIX_CRPS_RATIO = "appendix_crps_mean_ratio.png"

BLOG_PUBLISHED_FIGURES: tuple[str, ...] = (
    BLOG_FIG_UPC_GSIN,
    BLOG_FIG_GAMMA,
    BLOG_FIG_COLD_CHAIN,
    BLOG_FIG_DEMAND,
    BLOG_FIG_LADDER,
    BLOG_FIG_FACTORIAL,
    BLOG_FIG_FACTORIAL_W1_COUNT,
)

# (source path relative to ARTICLE_FIGURES_DIR, website basename)
SYNC_SOURCES: tuple[tuple[str, str], ...] = (
    (BLOG_FIG_GAMMA, BLOG_FIG_GAMMA),
    (BLOG_FIG_COLD_CHAIN, BLOG_FIG_COLD_CHAIN),
    (BLOG_FIG_DEMAND, BLOG_FIG_DEMAND),
    (BLOG_FIG_LADDER, BLOG_FIG_LADDER),
    (BLOG_FIG_FACTORIAL, BLOG_FIG_FACTORIAL),
    (BLOG_FIG_FACTORIAL_W1_COUNT, BLOG_FIG_FACTORIAL_W1_COUNT),
    (f"barcodes/{BLOG_FIG_UPC_GSIN}", BLOG_FIG_UPC_GSIN),
)
